DROP DATABASE IF EXISTS smart_order_db;
CREATE DATABASE smart_order_db;

USE smart_order_db;

-- Create M_USERS table.
DROP TABLE IF EXISTS M_USERS;
CREATE TABLE M_USERS (
    USER_ID VARCHAR(36) NOT NULL,
	USER_FULLNAME VARCHAR(36) NOT NULL,
	USER_NAME VARCHAR(36),
	USER_PASSWORD VARCHAR(64) NOT NULL,
	USER_PHONE VARCHAR(10) NOT NULL,
	USER_ADDRESS VARCHAR(64) NOT NULL,
	USER_TYPE TINYINT(1) NOT NULL COMMENT '0: End User, 1: Admin',
	USER_DELETE_FLG TINYINT(1) NOT NULL COMMENT '0:false, 1:true',
	USER_CREATED_BY VARCHAR(36) NOT NULL,
	USER_CREATED_AT BIGINT NOT NULL,
	USER_CREATED_AT_SYSTEM TIMESTAMP NOT NULL,
	USER_UPDATED_BY VARCHAR(36) NOT NULL,
	USER_UPDATED_AT BIGINT NOT NULL,
	USER_UPDATED_AT_SYSTEM VARCHAR(36) NOT NULL,

	-- Set PRIMARY KEY
	CONSTRAINT PK_M_USERS PRIMARY KEY (USER_ID),
	
	-- Set UNIQUE INDEX
	-- UNIQUE INDEX USER_PHONE_UNIQUE (USER_PHONE ASC) VISIBLE,
	UNIQUE INDEX USER_NAME_UNIQUE (USER_NAME ASC) VISIBLE
);